### ISSUE TITLE
Trailing slash in location needed

### ISSUE THREAD

**Issue by arthurzenika** [YunoHost-Apps/redirect_ynh#7]
We have a web application that when behind nginx, needs to have a trailing slash, so the default config : 

```
location /demo {
  proxy_path  http://internal.example.org:8080/;
[snip]
```

Needs to be modified to 
```
location /demo/ {
  proxy_path  http://internal.example.org:8080/;
[snip]
```

The "path" key in settings does include that trailing slash 
```
settings: 
  domain: example.org
  id: redirect
  [snip]
  path: /demo/
```

What is the right way to do this ? In the template ? Somewhere in the configuration ?
